# Generated by Django 5.1.4 on 2025-12-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_delete_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
