# Generated by Django 5.1.4 on 2025-12-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='advance_payment',
        ),
    ]
