# Generated by Django 5.1.4 on 2025-12-15 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_booking_advance_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email')]),
        ),
    ]
